/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./SafeYield.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { SafeYield } from "~~/contracts/SafeYield";`
 */
import type { ContractDeployment } from "~~/utils/contract";
import { SafeYield as SafeYield_LOCAL } from "./SafeYield.local";

const REMOTE = {
  11155111: {
    address: "0xb892c20480FE14607ba8780B8768A9eA3f8611bC",
    abi: [
      {
        type: "function",
        name: "MIN_AGENT_SCORE",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint16",
            internalType: "uint16",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "MIN_X402_AGENT_FEE",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint64",
            internalType: "uint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "SCORE_RELIABLE",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint16",
            internalType: "uint16",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "SCORE_STRONG",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint16",
            internalType: "uint16",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "computeYieldWaterfall",
        inputs: [
          {
            name: "circleId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "kind",
            type: "uint8",
            internalType: "enum SafeYield.CommitmentKind",
          },
          {
            name: "encryptedYieldReceived",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "encryptedCommitmentAmount",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "encryptedEmergencyTarget",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "encryptedReliabilityScore",
            type: "bytes32",
            internalType: "externalEuint16",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "createCircle",
        inputs: [
          {
            name: "rwaHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "encryptedContribution",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "encryptedRwaNav",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "encryptedAgentFeeCap",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [
          {
            name: "circleId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "executeYieldLock",
        inputs: [
          {
            name: "circleId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "passportId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "getPrivateCircle",
        inputs: [
          {
            name: "circleId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "contribution",
            type: "bytes32",
            internalType: "euint64",
          },
          {
            name: "rwaNav",
            type: "bytes32",
            internalType: "euint64",
          },
          {
            name: "yieldReceived",
            type: "bytes32",
            internalType: "euint64",
          },
          {
            name: "reserveBuffer",
            type: "bytes32",
            internalType: "euint64",
          },
          {
            name: "safeWithdrawal",
            type: "bytes32",
            internalType: "euint64",
          },
          {
            name: "userYieldShare",
            type: "bytes32",
            internalType: "euint64",
          },
          {
            name: "commitmentAmount",
            type: "bytes32",
            internalType: "euint64",
          },
          {
            name: "circleScore",
            type: "bytes32",
            internalType: "euint16",
          },
          {
            name: "commitmentActive",
            type: "bytes32",
            internalType: "ebool",
          },
          {
            name: "yieldShareEligible",
            type: "bytes32",
            internalType: "ebool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getPrivatePassport",
        inputs: [
          {
            name: "passportId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "x402FeePaid",
            type: "bytes32",
            internalType: "euint64",
          },
          {
            name: "requestedFee",
            type: "bytes32",
            internalType: "euint64",
          },
          {
            name: "agentScore",
            type: "bytes32",
            internalType: "euint16",
          },
          {
            name: "feeSettled",
            type: "bytes32",
            internalType: "ebool",
          },
          {
            name: "allowed",
            type: "bytes32",
            internalType: "ebool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getPublicCircle",
        inputs: [
          {
            name: "circleId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "owner",
            type: "address",
            internalType: "address",
          },
          {
            name: "rwaHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "status",
            type: "uint8",
            internalType: "enum SafeYield.CircleStatus",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "nextCircleId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "nextPassportId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "submitAgentPassport",
        inputs: [
          {
            name: "circleId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "taskType",
            type: "uint8",
            internalType: "uint8",
          },
          {
            name: "encryptedX402FeePaid",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "encryptedRequestedFee",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "encryptedAgentScore",
            type: "bytes32",
            internalType: "externalEuint16",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [
          {
            name: "passportId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "AgentPassportSubmitted",
        inputs: [
          {
            name: "passportId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "circleId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "agent",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "CircleCreated",
        inputs: [
          {
            name: "circleId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "owner",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "rwaHash",
            type: "bytes32",
            indexed: false,
            internalType: "bytes32",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "YieldLockExecuted",
        inputs: [
          {
            name: "circleId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "passportId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "YieldWaterfallComputed",
        inputs: [
          {
            name: "circleId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "kind",
            type: "uint8",
            indexed: true,
            internalType: "enum SafeYield.CommitmentKind",
          },
        ],
        anonymous: false,
      },
      {
        type: "error",
        name: "SenderNotAllowedToUseHandle",
        inputs: [
          {
            name: "handle",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
    ],
    deployedOnBlock: 10823312,
  },
} as const;

export const SafeYield = {
  ...REMOTE,
  ...SafeYield_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
